{% set version = "1.1.2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fnn
  version: {{ version|replace("-", "_") }}

source:
  fn: FNN_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/FNN_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/FNN/FNN_{{ version }}.tar.gz


  sha256: d50edffc9d8130d5a506b4fb5b1cbb7311dbb558662358d10e48c6efb99c2015

build:
  number: 0
  script: R CMD INSTALL --build .
  skip: True  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base

test:
  commands:
    - $R -e "library('FNN')"  # [not win]
    - "\"%R%\" -e \"library('FNN')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=FNN
  license: GPL (>= 2.1)
  summary: Cover-tree and kd-tree fast k-nearest neighbor search algorithms and related applications
    including KNN classification, regression and information measures are implemented.
  license_family: GPL3

extra:
  recipe-maintainers:
    - jsignell
