# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "BItb7qEtVItXx1go5M8uDZA+8icT6nJMoQSjtLGTgMGymHy/rHBulU9FgEyIs/ZnOFeOcRTFLLPPfmVxGc9A5BNiCmne8CaWstCzuXruOzFRNzfoRpJFwal4sX0uIF7KspYBzLauurFALXmGJvikCZ8ki8t5ZUW8JSnhTdF8JBGpeUEMW+S6L25GBP1mSMV5Y6xkq52wDHoX0TFjqC/+znmj9glyC+eglaXe4PU1WkAxvn4zd2Enp5gtKuQzJQMSwd7pynAnkv9i3K18FvExk5L7rbP9UdRZ4YC+YRn3DYJt4dk1O6cgovxiILBDfNH0WzmMdRMeS6YwtjeIx29xlvXl5OB5wO21Ed6974fex6HZ14n2bIWz3VXhSPatjqEQwBNtT4VWqH1Lx5wYqu7QZHb0Wty1M9eWsZ7MczwoEC0z1bebynniVP8Ksx1QVofWLgeJRxFzjqtOAOU7McNFAp+tpGnqCNCFKb3iAp2wMjTiY4swPTlJE/EqB8aay11Lni7Hxue4hXH9ihuptEubHnJtn3f6t9vkX4+wOAp0V4RzxGQDyZWIVOeRY53hgE0/GTHJ4MAQ6F4rpdbFxq78luw7NMrPR+/dwJkBMpCLcEGpxI7/APSv3qmbLbcnsbZ5Gmdj8Qw/T7EGucleyElEymfAxK0N3ss5I5Ta7ZOytBg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
