travis:
  secure:
    BINSTAR_TOKEN: BItb7qEtVItXx1go5M8uDZA+8icT6nJMoQSjtLGTgMGymHy/rHBulU9FgEyIs/ZnOFeOcRTFLLPPfmVxGc9A5BNiCmne8CaWstCzuXruOzFRNzfoRpJFwal4sX0uIF7KspYBzLauurFALXmGJvikCZ8ki8t5ZUW8JSnhTdF8JBGpeUEMW+S6L25GBP1mSMV5Y6xkq52wDHoX0TFjqC/+znmj9glyC+eglaXe4PU1WkAxvn4zd2Enp5gtKuQzJQMSwd7pynAnkv9i3K18FvExk5L7rbP9UdRZ4YC+YRn3DYJt4dk1O6cgovxiILBDfNH0WzmMdRMeS6YwtjeIx29xlvXl5OB5wO21Ed6974fex6HZ14n2bIWz3VXhSPatjqEQwBNtT4VWqH1Lx5wYqu7QZHb0Wty1M9eWsZ7MczwoEC0z1bebynniVP8Ksx1QVofWLgeJRxFzjqtOAOU7McNFAp+tpGnqCNCFKb3iAp2wMjTiY4swPTlJE/EqB8aay11Lni7Hxue4hXH9ihuptEubHnJtn3f6t9vkX4+wOAp0V4RzxGQDyZWIVOeRY53hgE0/GTHJ4MAQ6F4rpdbFxq78luw7NMrPR+/dwJkBMpCLcEGpxI7/APSv3qmbLbcnsbZ5Gmdj8Qw/T7EGucleyElEymfAxK0N3ss5I5Ta7ZOytBg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
