appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: PZBwnuguE7NmbE/rZXCCnLJpwqKB846cRAOq1EdVGABDrDa2eHK6AxLd8qZr+kEewY8B6fykB1k4C/Z7waI7Ty/G/QFVCFc6mhCW5CO6Xphggxr8iQf5ra76FBaGd5Zlq2SLTXobNuvSJj10Efku2jLZDale7A0daOwD90tLsK/prK4zC4Hiyr50wO+f6uhW4SP1J8fVfuscw4EQBJGt97/05W5YaEoUY6RjWkeyfS++fp/g71MgVS4VzrqrZ7oea20yScYlI05TIG2stYYBvYtha6reZscZxnLCLW7Er18u6iHqpW8G00aivpnMB9u8ZERT0HPiVUluU9IyedO4fJC7E+CqbiFg+47OrAks1APBeNntQZowRANKgFMS+cE4xu27trsoaWoSQADjAxTpFJetrEBDl8lWKPPtk7vEk/RJekoQeyJhOZ1+3tHILZBRgk/ZVz6B9L0o6pPbH3u60HtgcMapF+ILVFxSMpQYTSRxtcOSEN2fK2Pyx2T2cstk0mclskZPTaVjJnU1hobVGb32jsnL4VdQnayPAejSVCYn9pDDnOHhBAJ4hWYbFKlOZ3AuqnSNIxYULNbL2n/oWF4mLyglhpdBcDCzAkV7QkfxckqYKoPZck7ieVnj2RM8AMM2OUHLmWcqzxCQdQW35i6dIY55SIIM+USG8OOX/oo=
