travis:
  secure:
    BINSTAR_TOKEN: xyNGWcMkQpnE+++ppWldQeoOvJqGg1vDN7WSf5pvZtL+z6NCrX9pAO7lPMksDnuYv5A6t/00thjsv1NnHeoGD0/ADfG9wNSn4xpjibHKRarHycz2WElJSk7f3ec7yPnLaPLdxD0D+lpe/KbFM69Wl60FMhjs5LWr0qj2hW4ExzqWqLo17F7FgGz/hZJ+iUlx2NzDnN68B8vQ3WzLxsOS9eRlnT8fm50PoSp6H46k89xQ+mVwzLoQqn+n7/bLQMFEmbsmziDZVZLTHZoLMJOVLmezjqmPLX63Y8qPB8XP2193LjtNBrJvhK8wfSPj/138878nw8sIae0dR/u5SC4hBFExJUsDLOf0PugftMA5gsGNMWWMcrEdmSp6gP8/hAtOrP105JgZO21R4AUdy1BGK+zHaBRXmHJjCt6lMhe3IT6TEeHy4gh4eJC4DW11FSKgXgKVDsTXndaS0pRNEgLVNNi2B4Ju5TW48F8WQAzl2Row4srqGe+DK25w7BFmYVjl5+HJSAHs8SxAZGDZE0pXbadOI0RuT7MnZhpw29viz/ttVGE0QD50BdEkuP0pOuyfPOoSaDnl3+E9srWtqdQzQ4+pGPzQjJmsZm75/k5YHPMW6R9xrC1eVXU3fYghuA+lUW9XIfOgYf1BRIZkA99FckihU5DsOX68UfiplT2nP0I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
