travis:
  secure:
    BINSTAR_TOKEN: NKL9GaJMG25ZhQm/kes+zPsj7RDBcmCnad0+oJQsGCaFg8UkPjdlVociMTQz77aNXAHKTBuUAem6NcfOvg9R0vZcPMf6iy5nm78I6Le+VNOb0kTlQcpDOettPjgf4FVdjKtIz7PcSz5HO+GMCDvglqtiBa3KBP9zcE3FS/PClYIa4vLpLp8/2wJc7ejNUC8XrMINH1VvCkFHUF/bMx0rcI9S+dMMthMIWMsBPet+pt4RfrSXp6jIVmvvclNOZP1KXLK0XW+zv/hpPpQlfhQP44FkkxT9y7HkeKuHYe2z8Lzu8Vh6+57QOxJFJlQ9DkuVadPFz/HNYDNbeCvgM2MPzyzZgqx2oI1DwJUtrGtBVnZ4qL0L/HHgUzrjmIbPwND7Nc7HU7AkcJNDcmw/W8+0V1vVhQeSeOTRV++MYH8P5ABmG99vaxSVGasF51tjq26QY6bLhLUpgphNIcNHrY1ysp46e4XXqGTpEFEDUqUPBKSEX4ucTnFGurUuF4rQGfTAN04nnnxB2+3fFMEB378KMB/y2pxqzbjaWlTVbXOh/LlGjxA1dmWEj4KFvy1oYRy18/9GZd0DwZki0/jmIBXOok/H98cNQGroVWYljRJC/WEfHsOSicpYWGb4dqNbPdyQHqEU0oAgoFiIlnrqUkBj6zLE23qTro7L07Y/QWAZ+n8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
